name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    container: ros:galactic
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/urc-software
      - name: Install Dependencies
        shell: bash
        run: |
          source /opt/ros/galactic/setup.bash
          sudo apt-get update
          rosdep update --rosdistro=galactic
          rosdep install --from-paths . --ignore-src -y
      - name: Build
        shell: bash
        run: |
          source /opt/ros/galactic/setup.bash
          colcon build
      - name: Test
        shell: bash
        run: |
          source /opt/ros/galactic/setup.bash
          colcon test
